export const ADD_TO_RECENT = 'ADD_TO_RECENT';
export const LOAD_INITIAL_RECENTS = 'LOAD_INITIAL_RECENTS';
export const RECENTS_ERROR = 'RECENTS_ERROR';
export const RECENTS_CLEAR_ERROR = 'RECENTS_CLEAR_ERROR';