export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';
export const ADD_NOTE_TO_WISHLIST_ITEM = 'ADD_NOTE_TO_WISHLIST_ITEM';
export const LOAD_INITIAL_WISHLIST = 'LOAD_INITIAL_WISHLIST';
export const WISHLIST_ERROR = 'WISHLIST_ERROR';
export const WISHLIST_CLEAR_ERROR = 'WISHLIST_CLEAR_ERROR';